export const data = [
  {
    id: 9090,
    name: "Item1",
    price: 200,
    discount: 10,
    qty: 1,
    type: "fiction",
    imgurl: "https://place-hold.it/40.jpg",
  },
  {
    id: 9091,
    name: "Item2",
    price: 250,
    qty: 1,
    discount: 15,
    type: "literature",
    imgurl: "https://place-hold.it/40.jpg",
  },
  {
    id: 9092,
    name: "Item3",
    price: 320,
    discount: 5,
    qty: 1,
    type: "literature",
    imgurl: "https://place-hold.it/40.jpg",
  },
  {
    id: 9093,
    name: "Item4",
    price: 290,
    qty: 1,
    discount: 0,
    type: "thriller",
    imgurl: "https://place-hold.it/40.jpg",
  },
  {
    id: 9094,
    name: "Item5",
    price: 500,
    qty: 1,
    discount: 25,
    type: "thriller",
    imgurl: "https://place-hold.it/40.jpg",
  },
  {
    id: 9095,
    name: "Item6",
    price: 150,
    discount: 5,
    qty: 1,
    type: "literature",
    imgurl: "https://place-hold.it/40.jpg",
  },
  {
    id: 9096,
    name: "Item7",
    price: 700,
    qty: 1,
    discount: 22,
    type: "literature",
    imgurl: "https://place-hold.it/40.jpg",
  },
  {
    id: 9097,
    name: "Item8",
    price: 350,
    discount: 18,
    qty: 1,
    type: "fiction",
    imgurl: "https://place-hold.it/40.jpg",
  },
];
